### ISSUE TITLE
Everyone set her/his Github profile to 'public' so that ALTO board members are visible on Github.

### ISSUE THREAD

**Issue by cowboyMontana** [altoxml/board#1]

**Comment by cowboyMontana** [comment]
Nate, Brian, and Siang Hock all have 'private' profiles.

**Comment by bkgeig** [comment]
Done, though it took me a while to figure out how to change it.  Has to be done within ALTO settings, not personal. - Brian

**Comment by ntra00** [comment]
I can't figure out where to do this.

**Comment by cowboyMontana** [comment]
Greetings

It not obvious how to do this -- in fact it's well hidden.  Here's the
Github help page that explains how:
https://help.github.com/articles/publicizing-or-concealing-organization-membership/

Cheers,
Frederick

On Wed, Dec 10, 2014 at 6:15 AM, Nate Trail notifications@github.com
wrote:

> I can't figure out where to do this.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/altoxml/board/issues/1#issuecomment-66456709.

## 

Frederick Zarndt
Coronado CA 92118
USA

T. +1 801 361 3204
F. +1 877 723 3204
Skype frederickzarndt
Twitter @cowboyMontana
Website http://www.frederickzarndt.com
LinkedIn http://www.linkedin.com/in/frederickzarndt
