### ISSUE TITLE
Draft for board membership terms, criteria and recruiting new members

### ISSUE THREAD

**Issue by jukervin** [altoxml/board#20]

**Comment by jukervin** [comment]
Discussion from the board call:
- Three year with possibility to renew suggested.
- Divide members to three group and first group would be up for re-election next year.
- Chair rotation discussed. Maybe chair selection should be handled during face-to-face meeting.
- Frederik and Jukka will make changes to existing criteria as a draft.

**Comment by Jo-CCS** [comment]
Propose to adapt to 2-year time frame and accordingly to adapt to 2 groups.
Also change of position / company should be reason to re-confirm position on the board.

**Comment by cowboyMontana** [comment]
I'm in favor of 3 year term with 3 groups so as to reduce the possibility of board member churn and maintain at least 2/3 of the board with a experience on the board.

**Comment by cowboyMontana** [comment]
Added proposed additions about member terms to board membership criteria. Please review.

**Comment by jukervin** [comment]
http://altoxml.github.io/ALTO%20Board%20Membership%20Criteria.html

**Comment by jukervin** [comment]
Shall the new members be approved unanimously?
OT: Should archives be added in the list of membership criteria institutions?

**Comment by jukervin** [comment]
Discussion from a meeting:
- membership voting same as with the issues

**Comment by ntra00** [comment]
I think maybe we need an exception for board membership for a Library of Congress representative. We feel there should always be someone from LC.

**Comment by jukervin** [comment]
- One of the board members shall be from Library of Congress?
