### ISSUE TITLE
Contact someone technically competent with hOCR (possible board member).

### ISSUE THREAD

**Issue by cowboyMontana** [altoxml/board#23]

**Comment by splet** [comment]
Will approach Ray Smith/Ashok Popat (both Google) at DAS2016, if unsuccessful fall back to #7.

**Comment by splet** [comment]
Not been possible to get Ray or Ashok on board. Clemens to try TAMU contacts, Stefan to approach ABBYY.

**Comment by cneud** [comment]
Since Google appears to be a dead end, I will reach out to [@kba](https://github.com/kba) who is working on updating/clarifying the hOCR spec as you can see here http://kba.github.io/hocr-spec/1.2/.

**Comment by cneud** [comment]
Contacted @stweil about ALTO board membership on March 2nd 2017.

**Comment by evelienket** [comment]
The github-hocr 2 ALTO conversion is not yet on the software/tools list. (https://github.com/kba/hOCR-to-ALTO)

**Comment by cneud** [comment]
@evelienket Added this here: https://github.com/altoxml/documentation/wiki/Software
