### ISSUE TITLE
 Make a better and easy to maintain "http://altoxml.github.io"

### ISSUE THREAD

**Issue by evelienket** [altoxml/board#25]

**Comment by cneud** [comment]
Hello everyone, I've made a draft of a simple front page (attached - please save and rename to .html to view in a browser - GitHub don't allow html files as attachments): [index.html.txt](https://github.com/altoxml/board/files/94656/index.html.txt). 

Feedback welcome!

**Comment by Jo-CCS** [comment]
Hi Clemens,
very nice - I like it.
I would just propose to change sequence and to put those of general interest to top, means to place “ALTO Board Meeting Agenda and Minutes” at the end.
Also the other two elemens I would expand by default until having more than 3 sub-elements.
Attached the adapted result.
Jo
[index_adaptedJo.html.txt](https://github.com/altoxml/board/files/95558/index_adaptedJo.html.txt)

**Comment by Jo-CCS** [comment]
Hi Clemens,
 very nice - I like it.
 I would just propose to change sequence and to put those of general interest to top, means to place “ALTO Board Meeting Agenda and Minutes” at the end.
 Also the other two elemens I would expand by default until having more than 3 sub-elements.
 Attached the adapted result.
 Jo
[index_adaptedJo.html.txt](https://github.com/altoxml/board/files/95559/index_adaptedJo.html.txt)

**Comment by Jo-CCS** [comment]
Sorry, closed it by mistake. Did not found place to reverse the "Close" state. The delete of previous comment did not worked it out.

**Comment by cowboyMontana** [comment]
Hello Clemens and Jo,
Looks good to me too. Suggest you replace the current index.html with either Clemens' original version or Jo's revised version.  And then close this issue.
Frederick

**Comment by cneud** [comment]
I second the order of bullet points as proposed by Jo. Some further explanatory text and links may also still be added to the proposed new index.html - I am happy to collect suggestions and revise accordingly. 

One further change I would propose in this regard is to make a new branch "gh-pages" in the [board](https://github.com/altoxml/board) repository and move the html files for the meeting agenda and minutes there (similarly to what I did in [documentation](https://github.com/altoxml/documentation/tree/gh-pages)). This way we end up with - imho - cleaner URLs as e.g. http://altoxml.github.io/board/agenda/... and http://altoxml.github.io/board/minutes/... compared to having everything reside under http://altoxml.github.io/...

I can apply this suggestion once the board agrees.

**Comment by evelienket** [comment]
Because the github.io page for ALTO is a page that is indexed by search engines I would suggest to add a bit more introduction/explanation to this page like the following:

**Welcome to the ALTO XML Github pages**
ALTO (Analyzed Layout and Text Object) is a XML Schema that details technical metadata for describing the layout and content of physical text resources, such as pages of a book or a newspaper. It most commonly serves as an extension schema used within the Metadata Encoding and Transmission Schema (METS) administrative metadata section. However, ALTO instances can also exist as a standalone document used independently of METS.

The official page of this standard is http://loc.gov/standards/alto. There you will find
- all the [officially released versions](http://www.loc.gov/standards/alto/)
- information about the [community](http://www.loc.gov/standards/alto/) and the editorial board
- a list of [implementers](http://www.loc.gov/standards/alto/community/implementers.php)

"ALTO XML Github”  (https://github.com/altoxml) is used as the environment for maintenance and  development of the standard. On this location you will find
- the [issues that are under discussion](https://github.com/altoxml/schema/issues)
- [documentation](https://github.com/altoxml/documentation/wiki)
- [use cases]
- ALTO Board Meeting Agenda and Minutes

**Comment by Jo-CCS** [comment]
Makes sense to me. I agree.

**Comment by cneud** [comment]
Thank you both! I think the text from Evelien fits perfectly, I will update the draft index.html with all your suggestions so far.

**Comment by cneud** [comment]
Please find attached a revised version of the index.html with all the suggestions applied. 
[index.html.txt](https://github.com/altoxml/board/files/99463/index.html.txt)

**Comment by cneud** [comment]
Screenshot of above index.html

![screenshot](https://cloud.githubusercontent.com/assets/952378/13987990/60f5af44-f10a-11e5-954d-9b3301bbcf32.png)

**Comment by cneud** [comment]
Updated with new logo.
[index.html.txt](https://github.com/altoxml/board/files/270851/index.html.txt)

![screen](https://cloud.githubusercontent.com/assets/952378/15364921/91df8964-1d1e-11e6-9f52-4ada712a8cea.jpg)

**Comment by cowboyMontana** [comment]
Nice!

**Comment by cneud** [comment]
Revised again following the latest updates to logo+design.

[index.html.txt](https://github.com/altoxml/board/files/313856/index.html.txt)

![alto-gh](https://cloud.githubusercontent.com/assets/952378/16042434/eea12fdc-323a-11e6-9ec1-70beb23c3c7f.png)

**Comment by cneud** [comment]
I would now propose to exchange the current index.html at https://github.com/altoxml/altoxml.github.io with this one above, making this the https://altoxml.github.io landing page. This will require some changes (I am happy to make these adjustments if everyone agrees):
- The index.html currently at https://github.com/altoxml/altoxml.github.io for board agends/notes etc. needs to be moved to https://github.com/altoxml/board
- Accordingly, all subsequent updates to board agenda&minutes must also be made there instead.

**Comment by Jo-CCS** [comment]
So definately an agreement from my side, yes. This looks good.
Details about the content can be adapted later on, I think.
E.g. I would consider to have the linking to the schema releases and changes as extra topic at the beginning of the list as this is the core point.

**Comment by cowboyMontana** [comment]
looks good Clemens!
