### ISSUE TITLE
GitHub avatar

### ISSUE THREAD

**Issue by cneud** [altoxml/board#26]
I've made a very basic ALTO icon for use with our GitHub account. Would be keen to hear your thoughts!

![alto_icon](https://cloud.githubusercontent.com/assets/952378/12975857/93efd020-d0bf-11e5-952b-77e63f911d0b.png)

**Comment by bkgeig** [comment]
I think it looks great!  Thanks for creating it. - Brian

**Comment by cowboyMontana** [comment]
Hi Clemens,

The ALTO icon is fine.  We had been using the Library of Congress ALTO icon because (1) for  consistency between the 2 websites, and, maybe more importantly, (2) no one was ambitious enough to design an icon.  I'll put it on the agenda Feb 24...

Cheers,
Frederick

**Comment by cneud** [comment]
Thank you for your feedback. I also made an attempt at reusing the LoC ALTO banner for icon creation, unfortunately it won't lend itself easily to the adjustments required by GitHub.

![alto_icon_loc](https://cloud.githubusercontent.com/assets/952378/13045775/9510d7b0-d3d5-11e5-8067-2c95e971fc15.png)

**Comment by Jo-CCS** [comment]
Hi Clemens,

I appreciate your idea for the avatar.

Your proposal is expressing the “text” part of the ALTO very good.
What I personally miss are two other keywords, I see would like to have expressed as well: “layout” and “XML”

I do not have time right now for this, so here just a short draft out of my head.
Begin of March I have more time for this again, if there is interest.

(Image was not kept from mail / could not be uploaded. Provided now on shortlink)
http://redir.content-conversion.com/n93ts24

The layout part I would paint more abstract and the characters for ALTO need to be choosen to ensure you can get  the text “ALTO” immediately, as we are not that known everywhere.
I also would consider to unify the icon then with the one on LOC and to take the avatar into a banner style afterwards as well.

Kind regards,
Jo

**Comment by Jo-CCS** [comment]
As discussed on last call I asked Daniel (CEO of CCS) for invovlement of our marketing expert to make a proposal for a new logo. I got the confirmation for this. He will look into this next days / week. Before there was no time due to CeBit.

**Comment by Jo-CCS** [comment]
![alto1](https://cloud.githubusercontent.com/assets/6001497/14554212/a46c5faa-02eb-11e6-9d0f-00aba0f69e33.png)
![alto2](https://cloud.githubusercontent.com/assets/6001497/14554213/a470da08-02eb-11e6-9f66-5c2cd48e4caf.png)
Hi all,
here the proposals from David, our Marketing / Design expert.
He confirmed that trying to put all symbols of XML and Layout into it would be too much.
He also tried to synch to the design of the other LOC standards, I forwarded to him:
LoC:
http://www.loc.gov/standards/mix/
http://www.loc.gov/standards/premis/
http://www.loc.gov/standards/vracore/
http://www.loc.gov/standards/sru/
Please comment all not being in Hamburg. Then perhaps we can have a final discussion / come to a decission here in Hamburg next week.
Regards,
Jo

**Comment by cneud** [comment]
Like it! I'd vouch for the first one, as the second option is quite close in style and color to the logo of the DPLA, the Digital Public Library of America: http://www.apalaweb.org/wp-content/uploads/2014/02/DPLA_632x632.jpg

Regards,
Clemens

**Comment by cneud** [comment]
GitHub avatar has been updated with version 1 of the icons provided by CCS's marketing expert following the vote in the board call 18/05/2016.

**Comment by Jo-CCS** [comment]
While not having heared back from Nate yet for LOC website update I suppose that he is busy with other projects. I just made short trial for LOC redesign proposal as discussed on last call.
![loc_proposal](https://cloud.githubusercontent.com/assets/6001497/15568653/4b583e54-232d-11e6-83db-3a12b52fd4c5.png)
Feedback welcome.
I will send over the proposed HTML code and CSS style parallel to Nate in the hope that he has time to review and update LOC then shortly.

**Comment by cneud** [comment]
Looks excellent imho, thanks a lot!

**Comment by cowboyMontana** [comment]
very clear explanation of versioning.  nice layout too!

**Comment by ntra00** [comment]
Sorry for the delay in responding about changing the logo on the LC site. It will involve all the rest of the ALTO pages, so our design person is helping us implement it. I appreciate the package of fixes sent!

Nate

**Comment by cneud** [comment]
Closed following the change to new [GitHub avatar](https://github.com/altoxml) and [LoC webdesign](http://www.loc.gov/standards/alto/).
