### ISSUE TITLE
2016-10-27 Register MIME type for ALTO (application/xml+alto)

### ISSUE THREAD

**Issue by cowboyMontana** [altoxml/board#31]
Moved the text to Board wiki page to allow for history tracking.
https://github.com/altoxml/board/wiki/The-'application-alto-xml'-Media-Type

**Comment by jukervin** [comment]
Moved text to Board wiki to allow for history tracking.
https://github.com/altoxml/board/wiki/The-'application-alto-xml'-Media-Type

**Comment by jukervin** [comment]
Changes can be viewed from history
https://github.com/altoxml/board/wiki/The-'application-alto-xml'-Media-Type/_history

**Comment by jukervin** [comment]
4.2 and 4.3 needs rewriting.

**Comment by cneud** [comment]
Tracked in https://github.com/altoxml/schema/issues/40
