### ISSUE TITLE
Draft announcement v4.0

### ISSUE THREAD

**Issue by Jo-CCS** [altoxml/board#33]
Proposed text for draft announcement, including the licensing statement (added as first point).
Posting it here for re-usage on next release and common review.
As discussed on yesterdays call I assign to you for sending out to listserv and synching action with Nate.
Regards,
Jo

> Greetings,
> 
> The ALTO XML Editorial Board is pleased to announce that ALTO draft schema version 4.0 has been released. The schema can be found at https://github.com/altoxml/schema/blob/master/v4/alto-4-0-draft.xsd
> 
> Comments about the schema and its documentation as well as additional use cases for the new schema features are encouraged (Github account is required to make comments).
> Despite repeated review by board members and ALTO users, schema v3.1 allowed repeating Shape elements, which were not intended. 
> The ALTO board decided to release what was previously prepared as draft schema v3.2 as ALTO schema v4.0 including this fix. The summary of changes from ALTO schema v3.1 to v4.0:
> 
>   1. Changed schema version to 4.0
>   2. Changed namespace and targetNamespace to http://www.loc.gov/standards/alto/ns-v4#
>   3. Clarification and definition of the licensing to common standard "CC BY-SA 4.0" for this ALTO standard (with agreement of the authors)
> 	4. Added character based text description with new Glyph element and its subelement Variant (GlyphType, VariantType)
> 	5. Extended annotation for clarification of the difference of existing element ALTERNATIVE and Glyph/Variant
> 	6. Introduce generic "Processing" and deprecate "OcrProcessing"
> 	7. Introduce generic "processingStep" with "ProcessingStepType" and required attribute "ID" and deprecate "preProcessingStep", "ocrProcessingStep", "postProcessingStep"
> 	8. Add common vocabulary for "processingStep" comprising the "ContentGeneration", "ContentModification", "PreOperation", "PostOperation", "Other"
> 	9. Fix for the element Shape. The Shape element can now only be used once within a PageSpace or a TextLine as it was intended.
>   
> Note:
> According to base policy the ALTO schema is updated by whole numbers upon making changes that break backward compatibility (version 1 to version 2) and by decimals for changes that will not break backward compatibility. The namespace itself will only change on major versions (ns-v2 to ns-v3).
> 
> 
> Best regards,
> The ALTO Editorial Board
> 
> Joachim Bauer, Content Conversion Specialists (CCS)
> Raju Buddharaju, National Library Board, Singapore
> Brian Geiger, California Digital Newspaper Collection
> Jukka Kervinen, National Library of Finland
> Evelien Ket , Koninklijke Bibliotheek Netherlands
> Ralph Marschall, National Library of Luxembourg
> Jean-Philippe Moreux, Bibliotheque nationale de France
> Clemens Neudecker, Staatsbibliothek zu Berlin
> Stefan Pletschacher, University of Salford
> Ashok Popat, Google
> Art Rhyno, University of Windsor
> Nate Trail, Library of Congress
> Frederick Zarndt, www.frederickzarndt.com
>

**Comment by cowboyMontana** [comment]
4.0 announcement has been made.  closing this issue.
